const quotes = [
    { quote: "If you don't have time to read, you don't have the time (or the tools) to write. Simple as that.", 
    author: "Stephen King", },
    { quote: "You should write because you love the shape of stories and sentences and the creation of different words on a page. Writing comes from reading, and reading is the finest teacher of how to write.", 
    author: "Annie Proulx", },
    { quote: "Indeed, learning to write may be part of learning to read. For all I know, writing comes out of a superior devotion to reading.", 
    author: "Eudora Welty", },
    { quote: "Read, read, read. Read everything — trash, classics, good and bad, and see how they do it. Just like a carpenter who works as an apprentice and studies the master. Read! You'll absorb it. Then write. If it's good, you'll find out. If it's not, throw it out of the window.", 
    author: "William Faulkner", },
    { quote: "I kept always two books in my pocket: one to read, one to write in.", 
    author: "Robert Louis Stevenson", },
    { quote: "The Six Golden Rules of Writing: Read, read, read, and write, write, write.", 
    author: "Ernest Gaines", },
    { quote: "The greatest part of a writer’s time is spent in reading, in order to write; a man will turn over half a library to make one book.", 
    author: "Samuel Johnson", },
    { quote: "Read a thousand books, and your words will flow like a river.", 
    author: "Lisa See", },
    { quote: "One sure window into a person’s soul is his reading list.", 
    author: "Mary B. W. Tabor", },
    { quote: "If there's a book that you want to read, but it hasn't been written yet, then you must write it.", 
    author: "Toni Morrison", },
    { quote: "Everybody walks past a thousand story ideas every day. The good writers are the ones who see five or six of them. Most people don’t see any.", 
    author: "Orson Scott", },
    { quote: "Find a subject you care about and which you in your heart feel others should care about. It is this genuine caring, not your games with language, which will be the most compelling and seductive element in your style.", 
    author: "Stephen King", },
    { quote: "Most writers regard the truth as their most valuable possession, and therefore are most economical in its use.", 
    author: "Mark Twain", },
    { quote: "When I sit down to write a book, I do not say to myself, ‘I am going to produce a work of art.’ I write it because there is some lie that I want to expose, some fact to which I want to draw attention, and my initial concern is to get a hearing.", 
    author: "George Orwell", },
    { quote: "Write what disturbs you, what you fear, what you have not been willing to speak about. Be willing to be split open.", 
    author: "Natalie Goldberg", },
    { quote: "You have to write the book that wants to be written. And if the book will be too difficult for grown-ups, then you write it for children.", 
    author: "Madeleine L'Engle", },
    { quote: "How vain it is to sit down to write when you have not stood up to live.", 
    author: "Henry David Thoreau", },
    { quote: "Cheat your landlord if you can and must, but do not try to shortchange the Muse. It cannot be done. You can’t fake quality any more than you can fake a good meal.", 
    author: "William S. Burroughs", },
    { quote: "Write what should not be forgotten.", 
    author: "Isabel Allende", },
    { quote: "The story must strike a nerve in me. My heart should start pounding when I hear the first line in my head. I start trembling at the risk.", 
    author: "Susan Sontag", },
    { quote: "Sometimes the ideas just come to me. Other times I have to sweat and almost bleed to make ideas come. It’s a mysterious process, but I hope I never find out exactly how it works. I like a mystery, as you may have noticed.",
    author: "J.K. Rowling", },
    { quote: "As for ‘Write what you know,’ I was regularly told this as a beginner. I think it’s a very good rule and have always obeyed it. I write about imaginary countries, alien societies on other planets, dragons, wizards, the Napa Valley in 22002. I know these things. I know them better than anybody else possibly could, so it’s my duty to testify about them.", 
    author: "Ursula K. Le Guin", },
    { quote: "I’m very lucky in that I don’t understand the world yet. If I understood the world, it would be harder for me to write these books.", 
    author: "Mo Willems", },
    { quote: "Ideas are cheap. It’s the execution that is all important.", 
    author: "George R.R. Martin", },
    { quote: "If you wait for inspiration to write you’re not a writer, you’re a waiter.", 
    author: "Dan Poynter", },
];

const arrayDataSource = {
    name: 'Internal App Array',
    getQuote: () => 
        new Promise((resolve, reject) =>{
            const randomQuoteFromArray = quotes[Math.floor(Math.random() * quotes.length)];

            resolve(randomQuoteFromArray);
        }),
    }
